language: node_js
cache: yarn
node_js: 14
install: skip
os: linux
dist: focal

jobs:
  fast_finish: true
  include:
    - stage: verify
      if: branch != master AND type != pull_request
      install: yarn
      script:
        - yarn build
        - if [ "$CI_TEST" != "false" ]; then
            yarn test;
          fi
    - stage: build
      if: branch = master
      install: yarn
      script:
        - yarn build
        - chmod -R 777 target
      # https://docs.travis-ci.com/user/using-workspaces/
      workspaces:
        create:
          name: linux-shared
          paths:
            - target
            - flow-typed
            - typings
            - docs
            - node_modules

    - &test
      if: branch = master AND type = pull_request AND env(CI_TEST) != false
      stage: test
      install: skip
      script: yarn test
      workspaces:
        use: linux-shared
    - <<: *test
      node_js: 12
    - <<: *test
      if: branch = master AND type != pull_request AND env(CI_TEST) != false
      before_script:
        - if [ "$CC_TEST_REPORTER_ID" != "" ]; then
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
            chmod +x ./cc-test-reporter;
          ./cc-test-reporter before-build;
          fi
      script:
        - if [ "$CC_TEST_REPORTER_ID" != "" ]; then
            yarn test:report;
          else
            yarn test;
          fi
      after_script:
        - if [ "$CC_TEST_REPORTER_ID" != "" ]; then
            ./cc-test-reporter format-coverage -t lcov ./coverage/lcov.info;
            ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT;
          fi

    - stage: release
      if: branch = master AND type != pull_request AND env(CI_RELEASE) = true
      workspaces:
        use: linux-shared
      install: skip
      script: npx -p @qiwi/semrel-toolkit semrel -e @qiwi/semrel-config
